<?php

// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';

use Github\Client;
use Symfony\Component\HttpClient\HttplugClient;
use Symfony\Component\Dotenv\Dotenv;

/**
 * Search for code with GitHub API
 */
class CodeSearch
{
    /**
     * GitHub API client
     *
     * @var Github\Client
     */
    private $client;

    /**
     * GitHub API query string
     *
     * @var string
     */
    private $query;

    /**
     * Filename where output is to be saved
     *
     * @var string
     */
    private $filename;

    /**
     * Constructor
     *
     * @param string $query
     * @param string $filename
     */
    public function __construct($query, $filename)
    {
        $dotenv = new Dotenv();
        $dotenv->load(__DIR__.'/.env');
        $auth_token = $_ENV['AUTH_TOKEN'];
    
        // -----> hacky way to get the text matches... clean me up later! <-----
        // in vendor/knplabs/github-api/lib/Github/Api/Search.php add the following to the start of the code method:
        // $this->acceptHeaderValue = 'application/vnd.github.v3.text-match+json';

        $this->query = $query;
        $this->filename = $filename;
        $this->client = Client::createWithHttpClient(new HttplugClient());
        $this->client = new \Github\Client();
        $this->client->authenticate($auth_token, null, Github\Client::AUTH_ACCESS_TOKEN);
    }

    /**
     * Perform a code search
     *
     * @return void
     */
    public function search()
    {
        try {
            $files = $this->client->api('search')->code($this->query);

            $output = array_map(
                function ($file) {
                    $data = [
                        'repository' => $file['repository']['name'],
                        'path' => $file['path'],
                        'url' => $file['html_url'],
                        'text_matches' => $file['text_matches'][0]['fragment']
                    ];
                    return $data;
                }, 
                $files['items']
            );

            print("Files found: " . count($files));
            print("RESULTS: " . PHP_EOL);

            if ($this->filename) {
                file_put_contents("./$this->filename", print_r($output, true));
            }

        } catch (\Exception $e) {
            print $e->getMessage() . PHP_EOL;
        }
    }
}

